services:
  api:
    build: 
      context: .
    restart: always
    container_name: api-ex
    ports:
      - "5000:80"
    volumes:
      - .:/app:rw
    environment:
      - port=80
  db: 
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
